import "normalize.css";
import "./globals.css";

import type { Metadata } from "next";

import { lobster, inter } from "./fonts"

import { Header } from "@/components/header/header";


export const metadata: Metadata = {
  title: "Деревянные полки для кухни",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${lobster.variable} ${inter.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
